#pragma config(Sensor, S1,     Bumper,         sensorEV3_Touch)
#pragma config(Sensor, S2,     Wall,           sensorSONAR)
#pragma config(Sensor, S3,     Light,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          RightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          Grabber,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          LeftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task wallSensor()
{
}
task bumperSensor()
{
}
task lightSensor()
{
}

task main()
{
		while(true)
		{


		}


}
