#pragma config(Sensor, S1,     rightsensor,    sensorLightActive)
#pragma config(Sensor, S4,     leftsensor,     sensorLightActive)
#pragma config(Motor,  motorA,          rightmotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          leftmotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool rightsensorbool = false;
bool leftsensorbool= false;
task motors()
{
	while(true)
	{
		//	motor[motorA] = 10;
		//	motor[motorD] = 10;

	}
}
task lightsright{
	while(true)
	{

		if(SensorValue[rightsensor]< 25)
		{
			rightsensorbool = true;
		}
		else
		{
			rightsensorbool= false;
		}

	}
}
task lightsleft{
	while(true)
	{

		if(SensorValue[leftsensor]< 25)
		{
			leftsensorbool = true;
		}
		else
		{
			leftsensorbool= false;
		}

	}
}
task main()
{

	//	starttask lightsensor
	startTask (motors);
	startTask (lightsright);
	startTask (lightsleft);

	while(true)
	{
		motor[motorA] = 10;
		motor[motorD] = 10;
		if(rightsensorbool)
		{
			motor[motorA] = 10;
			motor[motorD] = -10;
			wait1Msec(100);

		}
		if( leftsensorbool)
		{
			motor[motorA] = -10;
			motor[motorD] = 10;
			wait1Msec(100);
		}

	}










	//	motor[motorA] = 100;
	//	motor[motorD] = 100;
	//	wait1Msec(10000);
	//	motor[motorA] =100;
	//	motor[motorD] =-100;
	//	wait1Msec(1000);
	//	motor[motorA] = 100;
	//	motor[motorD] = 100;


}
